import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const poppins = localFont({
    src: [
        { path: "/fonts/Poppins-Regular.ttf", weight: "400", style: "normal" },
        { path: "/fonts/Poppins-Medium.ttf", weight: "500", style: "normal" },
        { path: "/fonts/Poppins-SemiBold.ttf", weight: "600", style: "normal" },
        { path: "/fonts/Poppins-Bold.ttf", weight: "700", style: "normal" },
    ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
