import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { SessionProvider } from 'next-auth/react';

import { Toaster } from '@/components/ui/sonner';
import { auth } from '@/auth';

const poppins = localFont({
  src: [
    { path: '/fonts/Poppins-Regular.ttf', weight: '400', style: 'normal' },
    { path: '/fonts/Poppins-Medium.ttf', weight: '500', style: 'normal' },
    { path: '/fonts/Poppins-SemiBold.ttf', weight: '600', style: 'normal' },
    { path: '/fonts/Poppins-Bold.ttf', weight: '700', style: 'normal' },
  ],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang='en'>
      <SessionProvider session={session}>
        <body className={`${poppins.className} antialiased`}>
          {children}
          <Toaster />
        </body>
      </SessionProvider>
    </html>
  );
}
